title = "Vipul Behl"
baseURL = "https://vipulbehl.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "India"
email = "vipul@vipulbehl.com"
favicon = "img/favicon.png"
firstName = "Vipul"
lastName = "Behl"
phone = ""
profileImage = "img/VipulBehl.jpg"
showQr = false
showContact = true
showBoards  = false
showCertifications = false
showSocializations = true
sections = ["creations", "experience","skills","education"]


[params.google]

[params.google.analytics]
trackerID = "360049465"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/vipul-behl/"
    icon = "linkedin"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/vipulbehl"
    icon = "github"

[[params.handles]]
    link = "https://x.com/vipul_behl"
    name = "Twitter"
    icon = "twitter"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"